# Generated by Django 5.2.17 on 2026-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('calories', models.PositiveIntegerField(verbose_name='Калорийность на 100г (ккал)')),
                ('proteins', models.FloatField(verbose_name='Белки на 100г (г)')),
                ('fats', models.FloatField(verbose_name='Жиры на 100г (г)')),
                ('carbs', models.FloatField(verbose_name='Углеводы на 100г (г)')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
    ]
